name: Docker Build and Push

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      repo-user:
        required: true
        type: string
      repo-name:
        required: true
        type: string
    secrets:
      user:
        required: true
      pass:
        required: true
      token:
        required: true


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
      
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.user }} -p ${{ secrets.pass }}
      
    - name: Build Docker image
      run: docker build -t ${{ inputs.repo-user }}/hello-world:${{ inputs.tag }} .

    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
      
    - name: Push Docker image to Docker Hub
      run: docker push ${{ inputs.repo-user }}/hello-world:${{ inputs.tag }}
      
    - uses: howlowck/create-repo-action@v1.0
      with:
        repoName: ${{ inputs.repo-name }}
        repoVisibility: 'public'
        securityToken: ${{ secrets.token }}

