name: Docker Build and Push

on:
  workflow_call:
    inputs:
      key-word:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Run a one-line script
        run: echo ${{ inputs.key-word }}
